### ISSUE TITLE
how do u tie the license to specific ip or mac address?

### ISSUE THREAD

**Issue by hiqsociety** [hyperboloide/lk#5]
how do u tie the license to specific ip or mac address?

**Comment by fdelbos** [comment]
You can add all the info you want in the input.

**Comment by lordofscripts** [comment]
@hiqsociety  Add the MAC address to the JSON license. Then in your program, read the license and then validate the fields. In this case you take the MAC you read from the license file, use whatever method to obtain the current machine's MAC address and compare the two during validation.

There are two parts of the validation process:

- Validating the signature of the License to ensure it has not been tampered with
- Validating each of the (custom) attributes of the license. Here you have complete freedom.

But in this situation you must keep in mind that:

- Knowledgeable users *can* change the local MAC address but again not many people do.
- Nowadays computers usually have an Ethernet connection as well as a WiFi and even Bluetooth. Each of those have their own MAC address
